export const supportGroups = [
  { id: "macro-kii", title: "Macro Kii", intro: "Keep your work connected.", faqs: [
    { question: "What does Macro Kii mean?", answer: "Macro Kii means Macro Key Internal Integration. It brings notes, tasks, tables, calendars, research, and assisted work into one workspace. The Macro Key Menu framework is streamlined into the persistent Macro Panel." },
    { question: "What are Route, Turbo, and Vault for?", answer: "Route moves supported content between sections. Turbo sends written output to destinations shown in its interface. Vault keeps saved text, presets, and reusable macros available. Use the destinations offered by the current interface; these tools do not control every app on your computer." },
    { question: "Why is my task missing from Calendar?", answer: "Confirm that the task has the intended date, then navigate to that date in Calendar. Dated tasks connect with Calendar and Day Documents. If it is still missing, note the task name, date, and workspace and contact support. Keep a copy of any unsaved work before refreshing." },
    { question: "What is a Day Document?", answer: "A Day Document is a full document organized around a day. It gives your daily work and notes a shared context alongside Calendar events, alerts, and dated tasks. To Do also supports deeply nested subtasks for more detailed planning." },
    { question: "A Macro Panel action is not sending my content. What should I do?", answer: "Confirm the source content and the destination selected in the panel. Make sure that destination is offered for the action you are using. Copy any unsaved text before retrying once. If the action still fails, send support the action name, source, destination, and exact error. Avoid repeatedly submitting an action that could create duplicates." },
    { question: "Which plan should I start with?", answer: "Lite is a useful starting point for exploring the connected workflow. Essential is listed at $9.99 and Pro at $19.99. Check the current plan screen for billing frequency, included features, and usage allowances before choosing. Assisted features may have limits; unlimited AI usage is not promised." },
  ] },
  { id: "ao-verify", title: "AO Agent & Verify", intro: "Understand the answer and the evidence behind it.", faqs: [
    { question: "What is AO, and how is it different from Verify?", answer: "AO means Advanced Operator. It assists alongside your work and can hand output to destinations supported by the interface. Verify examines supported Workspace material with your context and returns findings with an evidence trust score." },
    { question: "What does the evidence trust score tell me?", answer: "The score indicates how strongly the evidence examined supports a finding. Review the supporting material, context, and uncertainty alongside the score. Verify is designed to support serious research and professional analysis, but a score does not guarantee truth or replace your judgment." },
    { question: "Verify gives an unexpected result. How can I improve it?", answer: "Confirm that you selected the intended document and supplied the context needed to assess it. Look for missing source material, ambiguous claims, or an incomplete document. Compare the finding with its evidence before relying on it. If the result still appears wrong, send a non-confidential example and a description of the discrepancy to support." },
    { question: "AO says it is unavailable. What should I do?", answer: "Keep a copy of any text you need, confirm your internet connection, and retry once after a short wait. If other pages load but AO still cannot answer, contact support with the product, approximate time, and exact message. You do not need to supply an API key to use this website's Ask AO chat." },
    { question: "Why does Ask AO turn red?", answer: "Red indicates Tech Support mode. AO uses it when helping with a technical problem or providing support guidance. Describe what happened and answer its follow-up question so troubleshooting can continue. When the problem is resolved, tell AO that it is working again." },
    { question: "Does chatting with AO contact a human?", answer: "AO is an automated assistant. A chat response is not confirmation that a human has received or reviewed your issue. For direct support, email support@akiiro.com. Never send passwords, API keys, payment details, or confidential documents in the chat." },
  ] },
  { id: "studio-a", title: "Studio-A", intro: "Touchscreen simplicity. Space to connect.", faqs: [
    { question: "What is Studio-A?", answer: "Studio-A is Akiiro's flagship touchscreen cyberdeck, specified with a Raspberry Pi 5, 8 GB of memory, 256 GB of storage, and a seven-inch touchscreen. Its design removes the fixed keyboard for a more portable experience. Macro Kii and Akiiro 3D are planned as interconnected experiences within it. Confirm the configuration of your order on the product page." },
    { question: "Which ports does Studio-A provide?", answer: "The Studio-A enclosure specification lists four USB-A ports, Ethernet, USB-C power, two Mini-HDMI ports, and A/V connectivity. These describe the custom device, not the bare Raspberry Pi board. Confirm the connector on your unit and the product documentation before choosing cables or adapters." },
    { question: "Studio-A does not turn on or the screen is blank. What can I check?", answer: "Check that the power supply specified for your unit is firmly connected to the USB-C power input and a working outlet. Note whether you see any power or display activity. If it remains blank, contact support with those observations and your order reference. Do not open the enclosure, disconnect internal cables, or erase the storage as a first troubleshooting step." },
    { question: "The touchscreen or a connected accessory is not responding. What should I do?", answer: "Describe whether the whole device is unresponsive or only one input or accessory. For an external accessory, inspect its cable and connector and check its compatibility with your unit. Do not unplug storage during a transfer. Save work before using a normal software restart if the interface is responsive. Contact support if the problem continues." },
    { question: "Can I use a keyboard?", answer: "Studio-A is built around touch rather than a fixed keyboard. A compatible separate keyboard can be used when needed. Confirm compatibility for your preferred accessory before purchasing it." },
  ] },
  { id: "akiiro-3d", title: "Akiiro 3D", intro: "For people who want to build their own.", faqs: [
    { question: "Who is Akiiro 3D for?", answer: "Akiiro 3D is for builders designing custom cyberdeck concepts and technology pieces. Studio-A offers a finished hardware direction, while Akiiro 3D serves people who want to explore and customize their own designs. The site currently identifies Akiiro 3D as beta." },
    { question: "A modeling tool or extrusion is not behaving as expected. What should I do?", answer: "Preserve your current work using the save or export options available before trying again. Note the tool, selected object, expected result, and actual result. Some beta functionality may be incomplete. Send support a screenshot and the shortest steps that reproduce the issue; do not overwrite your only copy while testing." },
    { question: "The 3D view is slow or does not load. What can I try?", answer: "Save your work if possible, close unnecessary browser tabs, and confirm your browser is current. Try a small new scene to distinguish a project-specific issue from a wider loading problem. If it persists, report your browser, device, and whether a new scene also fails." },
  ] },
  { id: "mind-map", title: "Akiiro Mind Map", intro: "Turn a subject into something you can explore.", faqs: [
    { question: "How do AI maps and Studio mode differ?", answer: "AI can turn a subject into a structured, interactive mind map. You can explore the breakdown and add connections. Studio mode lets you build maps yourself. Akiiro Mind Map is available through the Apple App Store." },
    { question: "My generated map is incomplete or misses the point. What should I do?", answer: "Give the subject a clearer scope and specify the areas you want covered. Review the generated structure and add or correct connections as needed. If generation stops unexpectedly, preserve the existing map, note any message, and contact support if a single retry does not help." },
    { question: "The app freezes or a map will not open. What should I do?", answer: "Record the app version, device, and whether the issue affects one map or all maps. Preserve any work you can and check for an available app update. Avoid deleting or reinstalling the app, or clearing its data, until you know your maps are safely backed up. Send support the steps leading to the freeze." },
  ] },
  { id: "io-vault", title: "IO Vault", intro: "A notebook for developers and curious minds.", faqs: [
    { question: "What can I do in IO Vault?", answer: "IO Vault combines a notebook-style workspace with learning and career agents, projects, mind maps, tables, and canvas tools. Its coding experience uses Monaco, with an IDE-style editing environment. An editor alone does not imply that every language or runtime can execute inside the app." },
    { question: "A project, canvas, or editor is not loading. What should I do?", answer: "Copy unsaved text where possible and confirm you are viewing the intended project. Note whether other project views open normally. Refresh only after preserving your work. If the problem persists, send the affected view, browser, and exact error to support without including private project contents." },
    { question: "An agent conversation stops responding. What should I do?", answer: "Preserve the prompt, confirm your connection, and retry once after a short wait. Note which agent and project were involved. If other workspace tools still work, include that detail when contacting support so the issue can be narrowed down." },
  ] },
  { id: "account-support", title: "Accounts, purchases & support", intro: "Get the right help with the right details.", faqs: [
    { question: "I cannot access my account or find my work. What should I do?", answer: "Confirm you are using the same product and sign-in method you used originally. Use the recovery options offered by that product. Avoid creating replacement accounts or deleting local data while investigating missing work. Contact support with the product and a description of the issue, never your password or verification codes." },
    { question: "Where can I ask about a purchase, subscription, or delivery?", answer: "Email support@akiiro.com with the product, purchase provider, order or receipt reference, and your question. Purchases may be handled by Apple, Stripe, or another identified provider. Current checkout and provider terms determine billing, cancellations, returns, and delivery details. Do not send full payment card information." },
    { question: "What should I include in a support email?", answer: "Include the product name, device and operating system, app or browser version, what you expected, what actually happened, and the steps that reproduce it. Add the approximate time and a screenshot with private information removed. Mention what you have already tried. Email support@akiiro.com to reach the team directly." },
  ] },
];
